name:                mediawiki-shell
version:             0.1.0.0
license:             BSD3
author:              "Me"
maintainer:          "example@example.com"
copyright:           "20XX Me"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Shell package for pulling mediawiki
category:            Web

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

executables:
  build-site:
    main:                Shakefile.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aeson
    - base >= 4.7 && < 5
    - comonad
    - comonad-extras
    - free
    - http-conduit
    - lens
    - lens-aeson
    - megaparsec
    - rio
    - pandoc
    - pandoc-types
    - shakebook
    - shake
    - slick
    - split
    - text-time
    - yaml
